code/tango_with_django_project/rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^like_category/$', views.like_category, name='like'),
    url(r'^add_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
    url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page')
    ,)

"""
The following is the non-querystring way to implement the url to track_url. Corresponding changes will have
to be made to the actual track_url view and "category.html". Refactoring to use querystrings so that you have an understanding
of how to implement.
"""
    # url(r'^goto/(?P<page_id>[\w\-}]+)/$', views.track_url, name='goto')

"""
Below URLs were used when we build a custom register, login, and logout
flow. Helpful for educational/informational purposes
"""
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout')

code/tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if succesful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/add_profile/' # Could probably make this more relative using namespaces


#This is called the urlpatterns "definition"; like you're defining any variable, in the form of a tuple
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace = 'rango')), #Adds app specific urls.py file
    #Add in this url pattern to override the default pattern in the Registration App
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
        )

code/tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

# Overwrites the save method to incoporate the conversion of name
# to the slug field; where the whitespaces are now hyphens through
# use of the slugify method
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "categories"

# Necessary for Python 2 users to establish encoding this way
# It is slightly variant for Python 3, where unicode is replaced with str
# Particularly helpful in debugging as it allows you to see field values
# as opposed to just seeing <Category: Category Object> because of encoding
# This is best practice, essentially making outputs human readable.
    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserPorfile to a User model instance.
    user = models.OneToOneField(User) # have to import the User model above from django.conrib.auth.models
    test_field = models.IntegerField(default=0)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', default="Is Anything Registering?")

    # Override the __unicode__() mehod to return something meaningful, from the linked User object
    def __unicode__(self):
        return self.user.username

code/tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the forms
    class Meta:
        # Provides an assocation between the ModelForm and
        # the Model that it is helping support
        model = Category
        fields = ['name']

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(widget=forms.widgets.TextInput, max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provides an association between the ModelForm and the Model
        model = Page
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present
        # Some fields may allow NULL values, so we may not want/need to include them...
        # Here, we are hiding the foreign key, which relates the Page to the Category
        # We can either exclude the category field from the form
        exclude = ['category']
        # or specify the fields to include (i.e. not include the category field)
        # equivalent alternative: fields = ('title','url','views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data['url']

        # If url is not empty and doesn't start with 'http://', then prepend
        # 'http://'
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['website', 'picture']

"""
Following forms are deprecated because we have refactored to use Django Registration Redux
App, which comes with it's own forms implementation for registering. Preserved below for
educational/infromational purposes
"""
# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())

#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password']

# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['website', 'picture']

code/tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse
#Import the Category model
from rango.models import Category, Page, UserProfile

from rango.forms import CategoryForm, PageForm, UserProfileForm # UserForm, UserProfileForm

from rango.utils import get_category_list

from datetime import datetime

from rango.bing_search import run_query

from registration.users import UserModel


def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by number of likes in descending order.
    # Retrieve the top 5 only -- or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to the template engine
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {'categories': category_list}

    # Excercise 7.4 Modify the index page to also include the top 5 most viewed pages.
    page_list = Page.objects.order_by('-views')[:5]
    context_dict['pages'] = page_list

    # Get the number of visits to the site.
    # New implementation using session.get()
    reset_last_visit_time = False
    visits = request.session.get('visits')
    if not visits:
        visits = 1

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        # If it's been more than a day since the last visit...
        if (datetime.now() - last_visit_time).seconds > 0:
            visits = visits + 1
            # ... and flag that the cookie last visit needs to be updated for new
            # visit stats
            reset_last_visit_time = True

    else:
        # Cookie last_visit doesn't exist, so flag that it should be set
        # because it will now be set
        reset_last_visit_time = True

    if reset_last_visit_time:
        # STA comment - setting cookies on the server side, which is connected to
        # sessionID. This is done through the request object.
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    context_dict['visits'] = visits
    response = render(request, 'rango/index.html', context_dict)
    return response

def about(request):
    visits = request.session.get('visits')
    context_dict = {}
    if visits:
        context_dict['visits'] = visits
    return render(request, 'rango/about.html', context_dict)

def category(request, category_name_slug):
    # Create a context dictionary, specific to category view, which we
    # will pass to the template rendering engine.
    context_dict = {}
    result_list = []

    # Next few lines ares brought over from deprecated searh() view
    if request.method == 'POST':
        query = request.POST['query'].strip() #Not sure what strip() does yet

        if query:
            # Run our Bing function to get the results list
            result_list = run_query(query)
            context_dict['result_list'] = result_list

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception
        # So the .get() method returns a model instance (object) or raises an exception
        category = Category.objects.get(slug=category_name_slug)
        # Let's see if the below works for incrementing w/o an if statement
        category.views += 1
        category.save()
        context_dict['category_name'] = category.name

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance (object).
        pages = Page.objects.filter(category=category).order_by('-views')

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # This is necessary for the if statement that we perform in the category
        # template, where we confirm that the category being called upon exists
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category; there is no
        # matching category_name_slug. If this occurs, we don't do anything
        # The template displays the "no category" message for us
        # Slight Modification
        context_dict['category_slug'] =  category_name_slug
        pass

    # Now go render the reponse and return it to the client
    return render(request, 'rango/category.html' , context_dict)

@login_required
def add_category(request):
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # If the supplied form contained errors, making it NOT valid, print these
            # errors to the terminal
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details
        # (i.e. upon first load)
        form = CategoryForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    # A HTTP POST?
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method =='POST':
        form = PageForm(request.POST)
        # Is the Form Valid?
        if form.is_valid():
            # Save the new page to the DB
            if cat:
                page = form.save(commit=False)
                page.category = cat
                # page.views = 0 from original, but doesn't seem necessary
                page.save()
            # Return user to category page; Tango with Django suggests a redirect
            # would be better here but does not show how to implement
            return category(request, category_name_slug)
        else:
            # Show any errors if the form is not valid
            print form.errors
    else:
        # If the request was a GET, render using the add_page template
        form = PageForm()

    # Need to pass category slug directly in the event that the cat does not exist,
    # but rango/category/<category_name_slug>/add_page has been navigated to
    context_dict = {'form': form, 'category': cat, 'category_slug': category_name_slug}
    return render(request, 'rango/add_page.html', context_dict)


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})

# Use the login_required() decorator to ensure only those logged in can access the view whereby they can logout

def search(request):
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip() #Not sure what strip() does yet

        if query:
            # Run our Bing function to get the results list
            result_list = run_query(query)

    return render(request, 'search/search.html', {'result_list': result_list})

def track_url(request):
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                return redirect(page.url)
            except Page.DoesNotExist:
                pass
        return redirect('index')

#             profile = profile_form.save(commit=False)
#             profile.user = user # profile.user comes from our UserProfile model

def register_profile(request):
    registered = False

    if request.method == 'POST':
        form = UserProfileForm(data = request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            User = UserModel() # imported above
            current_user = User.objects.get(username = request.user.username)
            profile.user = current_user # form.user link comes from request object
            print profile.user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance to the DB
            profile.save()
            # Update our variable to tell the template registeration was succesful
            registered = True
            return index(request)
        else:
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details
        # (i.e. upon first load)
        form = UserProfileForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'registration/profile_registration.html', {'form': form})

@login_required
def like_category(request):

    category_id = None
    if request.method == 'GET':
        category_id = request.GET['category_id']

    likes = 0
    if category_id:
            category = Category.objects.get(id=category_id)
            if category:
                category.likes += 1
                likes = category.likes
                category.save()

    return HttpResponse(likes)

@login_required
def auto_add_page(request):
    context_dict = {}

    print "Auto Add Page being called"
    if request.method == 'GET':
        category = Category.objects.get(id=int(request.GET['category_id']))

    if category:

code/tango_with_django_project/templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About Rango</h1>
    </div>

    <div>
        This is <strong>Rango's about page.</strong><br />
        {% if visits %}
        You have visited the Rango site {{visits}} time{% if visits > 1 %}s{% endif %}.<br />
        {% endif %}
        Here's a picture of Rango!<br />
        <img src="{% static "images/alphaomega.png" %}" alt="Picture of Greek Symbol for Alpha and Omega" /><br />
        Return to <a href='/rango/'>Rango's Home Page</a><br />
        <button onClick="alert('You clicked the button using Javascript.');">
            Click Me - I run Javascript
        </button>

        <button id="about-btn"> Click Me - I'm Javascript on Speed</button>
        <div id="msg">Hello</div>
        <p>is a example</p>
        <p>This is another example</p>

    </div>
{% endblock %}

code/tango_with_django_project/templates/rango/add_category.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Add Category{% endblock %}

{% block body_block %}

    <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading">Add a Category</h2>

        {% csrf_token %}
        {% bootstrap_form form show_label=False %}

    <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
    </form>
{% endblock %}

<!--

    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}


Slightly older version
        <div class="page-header">
            <h1>Add a Category</h1>
        </div>

        <form id="category_form" method="post" action="/rango/add_category/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Category" />
        </form>
-->

code/tango_with_django_project/templates/rango/add_page.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Add Page{% endblock %}

{% block body_block %}
<!--STA:Deleted the link to the signin.css from bootstrap b/c it changed the background color. Not sure why Tango is having us do this, no other styling elements are picked up, making all the form pages having a different background color than the rest of the app. This is OK for the signin page, but only makes sense there-->
{% if category %}
    <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category_slug %}">
    <h2 class="form-signin-heading">Add a Page to <a href="{% url 'rango:category' category_slug %}">{{ category.name }}</a></h2>
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}

    <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
    </form>
{% else %}
    <p>This category does not exist.</p>
{% endif %}
{% endblock %}

<!--
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}</br>
        {{ field }}</br>
    {% endfor %}
-->

<!--
        <div class="page-header">
            <h1>Add a Page to {{ category.name }}</h1>
        </div>

        <form id="page_form" method="post" action="{% url 'rango:add_page' category_slug %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
            <p>
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            </p>
            {% endfor %}

            <input type="submit" name="submit" value="Add Page"/>
        </form>
-->

code/tango_with_django_project/templates/rango/category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
        <div class="page-header">
            <h1>{{ category_name }}</h1>

            <p>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
                {% if user.is_authenticated %}
                    <button id="like" data-catid="{{category.id}}" class="btn btn-primary" type="button">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    Like
                    </button>
                {% endif %}
            </p>

        </div>
        {% if category %}

            <div id="pages">
                {% if pages %}
                    <ul>
                    {% for page in pages %}
                        <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }} </a>
                        {% if page.views > 1 %}
                            ({{ page.views }} views)
                        {% elif page.views == 1 %}
                            ({{ page.views }} view)
                        {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong><br />
                {% endif %}
            </div>

            {% if user.is_authenticated %}
                <a href="/rango/category/{{ category.slug }}/add_page/">Would you like to manually add more pages to {{ category.name }}?</a>

                <div class="page-header">
                    <h1>Search with Rango</h1>
                </div>

                <div class="row">

                    <div class="panel">
                    <br/>
                        <div class="panel-body">
                            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:category' category.slug %}">
                            {% csrf_token %}
                            <!-- Display the search form elements here -->
                                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                                <br/>
                            </form>
                        <br/>


                                {% if result_list %}
                                <div class="panel panel-primary">
                                    <div class="panel-heading">
                                        <h3 class ="panel-title">Results</h3>
                                    </div>
                                    <!-- Display search results in an ordered list -->
                                        <div class="panel-body">
                                            <div class="list-group">
                                                {% for result in result_list %}
                                                    <div class="list-group-item">
                                                        <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}&nbsp</a>
                                                        <button  class="add_page btn btn-mini btn-info" data-title="{{ result.title }}" data-link="{{ result.link }}" data-catid="{{ category.id }}" type="button">
                                                        Add Page to Category
                                                        </button>
                                                        </h4>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

        {% else %}
            The specified category {{category_name}} does not exist!<br/>
            Would you like to <a href="/rango/add_category/">Add a {{ category_slug }} Category to Rango?</a>
        {% endif %}

{% endblock %}

code/tango_with_django_project/templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-pills nav-stacked">
    {% for c in cats %}
        {% if c == act_cat %}
            <li role="presentation" class="active">
        {% else %}
            <li role="presentation">
        {% endif %}
        <a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a></li>
    {% endfor %}

{% else %}
    <li role="presentation"><strong>There are no categories present.</strong></li>
    </ul>
{% endif %}

code/tango_with_django_project/templates/rango/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block body_block %}
        <div class="page-header">
            {% if user.is_authenticated %}
            <h1>Rango says...hello {{ user.username }}!</h1>
            {% else %}
            <h1>Rango says...hello world!</h1>
            {% endif %}
        </div>

        <div class="row placeholders">
            <div class="col-xs-12 col-sm-6 placeholder">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>Top Categories</h4>
                    </div>
                </div>

                {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                        <!-- Making the list a list of hyperlinks that refer to slug/url -->
                        <li class='list-group-item'><a href="{% url 'rango:category' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}<br />
            </div>

            <div class="col-xs-12 col-sm-6 placeholder">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>Top Pages</h4>
                    </div>
                </div>

                {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                        <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages are yet available.</strong>
                {% endif %}<br />
            </div>
        </div>

        <p>You have visited the site {{ visits }} times! Thanks for coming! </p>
{% endblock %}

code/tango_with_django_project/templates/rango/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block body_block %}
        <h1>Login to Rango</h1>

        <form id="login_form" method="post" action="{% url 'rango:login' %}">
            {% csrf_token %}
            <p>Username: <input type="text" name="username" value="" size="50" /></p>
            <p>Password: <input type="text" name="password" value="" size="50" /></p>

            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}

            <input type="submit" value="submit" />
        </form>

{% endblock %}

code/tango_with_django_project/templates/rango/pages.html
{% if pages %}
    <ul>
    {% for page in pages %}
        <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }} </a>
        {% if page.views > 1 %}
            ({{ page.views }} views)
        {% elif page.views == 1 %}
            ({{ page.views }} view)
        {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong><br />
{% endif %}

code/tango_with_django_project/templates/rango/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block body_block %}
        <h1>Register with Rango</h1>

        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to homepage</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Display each form. The as_p method wraps each element in a paragraph (<p>) element.
            This ensures each element appears on a new line, making everything look neater and saves the for loop -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}

code/tango_with_django_project/templates/rango/restricted.html
{% extends 'base.html' %}

{% block title %}Restricted{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Restricted Page</h1>
    </div>
    <div>
        Since you're logged in, you can see this text!
    </div>
{% endblock %}