code/tango_with_django_project/rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^like_category/$', views.like_category, name='like'),
    url(r'^add_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
    url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page')
    ,)

"""
The following is the non-querystring way to implement the url to track_url. Corresponding changes will have
to be made to the actual track_url view and "category.html". Refactoring to use querystrings so that you have an understanding
of how to implement.
"""
    # url(r'^goto/(?P<page_id>[\w\-}]+)/$', views.track_url, name='goto')

"""
Below URLs were used when we build a custom register, login, and logout
flow. Helpful for educational/informational purposes
"""
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout')

code/tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if succesful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/add_profile/' # Could probably make this more relative using namespaces


#This is called the urlpatterns "definition"; like you're defining any variable, in the form of a tuple
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace = 'rango')), #Adds app specific urls.py file
    #Add in this url pattern to override the default pattern in the Registration App
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
        )

code/tango_with_django_project/templates/search/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}

<div class="page-header">
    <h1>Search with Rango</h1>
</div>

<div class="row">

    <div class="panel">
        <br/>
        <div class="panel-body">
            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
                {% csrf_token %}
                <!-- Display the search form elements here -->
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                <br/>
            </form>
            <br/>


            <div class="panel panel-primary">
                {% if result_list %}
                    <div class="panel-heading">
                        <h3 class ="panel-title">Results</h3>
                    </div>
                    <!-- Display search results in an ordered list -->
                        <div class="panel-body">
                            <div class="list-group">
                                {% for result in result_list %}
                                    <div class="list-group-item">
                                        <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}